# Generated by Django 3.1.14 on 2023-08-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, null=True)),
                ('last_name', models.CharField(default='', max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=100, null=True)),
                ('password', models.CharField(default='', max_length=255, null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('gender', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
