# Generated by Django 3.1.14 on 2023-08-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0002_course_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=100, null=True)),
                ('video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_preview', models.BooleanField(default=False)),
            ],
        ),
    ]
