# Generated by Django 3.1.14 on 2023-08-03 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0003_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ELearning.course_details'),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
