# Generated by Django 3.1.14 on 2023-08-09 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0005_learning_prereq_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearning.course_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearning.signup')),
            ],
        ),
    ]
