# Generated by Django 3.1.14 on 2023-08-09 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ELearning.user_course'),
        ),
    ]
